name: Build with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Certifique-se de que esta é a versão correta do seu projeto

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov httpx # Instala as ferramentas de teste

      - name: Run Tests and Generate Coverage Report
        run: pytest --cov=app --cov-report=xml:coverage.xml


      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
            args: "-Dsonar.projectKey=crispolas_Projeto-Sonar -Dsonar.organization=sonar-projeto -Dsonar.tests=test -X"
            projectBaseDir: .
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: https://sonarcloud.io

